### ISSUE TITLE
MDM registration race condition

### ISSUE THREAD

**Issue by ben-pearce** [Boostport/setup-cloudflare-warp#11]
I have been experimenting with Cloudflare WARP cli in GitHub actions and found your workflow which I have been testing with.

I ran into an issue where the MDM policy is not applied by the daemon immediately after the config file is written `/var/lib/cloudflare-warp/mdm.xml`.  In actual fact it takes 2-3 secs before the policy becomes active.

This results in WARP client instead connecting to 'free' generic WARP account instead of a teams device enrollment, so my Cloudflare Access applications are not reachable by the workspace.

I have implemented a solution which repeatedly checks the output of `warp-cli settings` to see if the MDM policy is applied and the device is enrolled in the organization, at which point it continues as normal invoking `warp-cli connect`. Of note is that the call to `warp-cli register` is not necessary when using MDM enrolled devices, so that has been removed:

https://github.com/Boostport/setup-cloudflare-warp/compare/main...ben-pearce:setup-cloudflare-warp:main

I have only tested with the most recent version of the warp client for Linux (`2023.3.398` at present). I am not sure if this is backwards compatible with old versions. I do not know if this is functionality that has changed more recently in the latest versions of WARP client.

I personally believe this is poor design on Cloudflare's part, the MDM policy should be able to be passed in as a command line argument (ex: `--mdm-file /var/lib....`) which would force the daemon to use that config file immediately.

**Comment by F21** [comment]
@ben-pearce Thanks so much for testing out this action and opening this issue. Just had a lookt at the commits on your fork and the solution looks very reasonable. Would you be able to open a PR so that we can get the fix in here?
