### ISSUE TITLE
golang

### ISSUE THREAD

**Issue by gedw99** [Boostport/setup-cloudflare-warp#120]
had a look... your just calls the per OS installer and then doing a exec.

I wrote the same thing in golang calling the CF golang binary.

also runs in GitHub CI, but also any other place I need it.

**Comment by F21** [comment]
Can you expand on what you'd like to see changed / updated? It's a bit unclear at the moment.

**Comment by F21** [comment]
In general, GitHub actions are written in JavaScript or deployed in a docker container. In the case of this action, JavaScript was easier, as we are just running a few commands and do not need any extra tools built into a docker container. The [actions/toolkit](https://github.com/actions/toolkit) is pretty useful and abstracts a lot of stuff away too.
